import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Grid, LinearProgress, Rating } from '@mui/material';
const RatingCard = ({ totalReview }) => {
    return (_jsxs("div", { className: "border p-5 rounded-md", children: [_jsxs("div", { className: "flex items-center space-x-3 pb-10", children: [_jsx(Rating, { name: "read-only", value: 4.6, precision: 0.5, readOnly: true }), _jsxs("p", { className: "opacity-60", children: [totalReview, " Ratings"] })] }), _jsx(Box, { children: _jsxs(Grid, { container: true, justifyContent: "center", alignItems: "center", gap: 2, children: [_jsx(Grid, { size: 2, children: _jsx("p", { className: "p-0", children: "Excellent" }) }), _jsx(Grid, { size: 7, children: _jsx(LinearProgress, { className: "", sx: { bgcolor: "#d0d0d0", borderRadius: 4, height: 7 }, variant: "determinate", value: 40, color: "success" }) }), _jsx(Grid, { size: 2, children: _jsx("p", { className: "opacity-50 p-2", children: "19259" }) })] }) }), _jsx(Box, { children: _jsxs(Grid, { container: true, justifyContent: "center", alignItems: "center", gap: 2, children: [_jsx(Grid, { size: 2, children: _jsx("p", { className: "p-0", children: "Very Good" }) }), _jsx(Grid, { size: 7, children: _jsx(LinearProgress, { className: "", sx: { bgcolor: "#d0d0d0", borderRadius: 4, height: 7 }, variant: "determinate", value: 30, color: "success" }) }), _jsx(Grid, { size: 2, children: _jsx("p", { className: "opacity-50 p-2", children: "19259" }) })] }) }), _jsx(Box, { children: _jsxs(Grid, { container: true, justifyContent: "center", alignItems: "center", gap: 2, children: [_jsx(Grid, { size: 2, children: _jsx("p", { className: "p-0", children: "Good" }) }), _jsx(Grid, { size: 7, children: _jsx(LinearProgress, { className: "bg-[#885c0a]", sx: { bgcolor: "#d0d0d0", borderRadius: 4, height: 7 }, variant: "determinate", value: 25 }) }), _jsx(Grid, { size: 2, children: _jsx("p", { className: "opacity-50 p-2", children: "19259" }) })] }) }), _jsx(Box, { children: _jsxs(Grid, { container: true, justifyContent: "center", alignItems: "center", gap: 2, children: [_jsx(Grid, { size: 2, children: _jsx("p", { className: "p-0", children: "Avarage" }) }), _jsx(Grid, { size: 7, children: _jsx(LinearProgress, { className: "", sx: {
                                    bgcolor: "#d0d0d0",
                                    borderRadius: 4,
                                    height: 7,
                                    "& .MuiLinearProgress-bar": {
                                        bgcolor: "#885c0a", // stroke color
                                    },
                                }, variant: "determinate", value: 21, color: "success" }) }), _jsx(Grid, { size: 2, children: _jsx("p", { className: "opacity-50 p-2", children: "19259" }) })] }) }), _jsx(Box, { children: _jsxs(Grid, { container: true, justifyContent: "center", alignItems: "center", gap: 2, children: [_jsx(Grid, { size: 2, children: _jsx("p", { className: "p-0", children: "Poor" }) }), _jsx(Grid, { size: 7, children: _jsx(LinearProgress, { className: "", sx: { bgcolor: "#d0d0d0", borderRadius: 4, height: 7 }, variant: "determinate", value: 10, color: "error" }) }), _jsx(Grid, { size: 2, children: _jsx("p", { className: "opacity-50 p-2", children: "19259" }) })] }) })] }));
};
export default RatingCard;
